### ISSUE TITLE
Improve: model's functions documentation

### ISSUE THREAD

**Issue by miguelms95** [zeeraw/gradient#5]
Hi, first of all, thanks for the gem! 
It would be great to describe at README the functions in the models.

I want to get a color interpolation and print as background in a table, I need the hexadecimal color, i had to inspect the code to find that it could be done with **color.hex**
```
gradient = Gradient::Map.new(
      Gradient::Point.new(0, Color::RGB.new(255, 255, 255), 1.0),
      Gradient::Point.new(1, Color::RGB.new(226, 82, 82), 1.0)
    )
gradient.at(0.5).color.hex
```

I suggest to add this info to the readme and the other functions... it could help.

**Comment by zeevallin** [comment]
Hi, I haven’t touched this gem in a while. I might get around to it if I
get the time. A merge request with any documentation changes you’d like to
see would be much appreciated.

**Comment by miguelms95** [comment]
Ok! I'll do it soon

**Comment by miguelms95** [comment]
Here is the PR: https://github.com/zeeraw/gradient/pull/6
